'''
Project Euler Problem 2: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sume of the even-valued terms.

Answer: 4613732
https://projecteuler.net/problem=2
'''
#!/usr/bin/env python3
num1 = 1
num2 = 2
temp = 0
total = 0

while temp <= 4000000:
    temp = num2
    if temp % 2 == 0:
        total += temp
    temp = num1 + num2
    num1 = num2
    num2 = temp

print (total)
